# Generated by Django 2.1.7 on 2019-03-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('st', 'START'), ('cm', 'COMMON'), ('end', 'END')], default='cm', max_length=5),
        ),
    ]
