# Generated by Django 2.1.7 on 2019-03-16 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0002_question_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jump',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='jump',
            name='option',
        ),
        migrations.RemoveField(
            model_name='jump',
            name='question_to',
        ),
        migrations.AddField(
            model_name='option',
            name='question_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sim.Question'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Jump',
        ),
    ]
