# Generated by Django 2.1.7 on 2019-03-16 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0003_auto_20190316_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='question_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sim.Question'),
        ),
    ]
