# Generated by Django 2.1.7 on 2019-03-16 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0004_auto_20190316_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.TextField()),
                ('value', models.IntegerField()),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Param')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('session_key', 'param')},
        ),
    ]
