# Generated by Django 2.1.7 on 2019-03-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0005_auto_20190316_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='param',
            name='default_value',
            field=models.IntegerField(default=0),
        ),
    ]
