# Generated by Django 2.1.7 on 2019-03-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0007_auto_20190316_1637'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('answer', 'name'), ('answer', 'bottom_line', 'upper_line')},
        ),
    ]
