# Generated by Django 2.1.7 on 2019-03-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0009_auto_20190316_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
